name: CI

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - main
    - develop

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: --deny warnings

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Remove Broken WSL bash executable
      if: ${{ matrix.os == 'windows-latest' }}
      shell: cmd
      run: |
        takeown /F C:\Windows\System32\bash.exe
        icacls C:\Windows\System32\bash.exe /grant administrators:F
        del C:\Windows\System32\bash.exe

    - name: Install Rust Toolchain Components
      uses: actions-rs/toolchain@v1.0.6
      with:
        override: true
        toolchain: stable
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@v2.7.3

    - name: Check Lockfile
      run: |
        # cargo update --locked --package just

    - name: Test
      run: cargo test --all

    - name: Clippy
      run: cargo clippy --all --all-targets

    - name: Format
      run: cargo fmt --all -- --check
