name: Release

on:
  push:
    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        target:
        - aarch64-apple-darwin
        # - aarch64-unknown-linux-musl
        # - armv7-unknown-linux-musleabihf
        - x86_64-apple-darwin
        - x86_64-pc-windows-msvc
        - x86_64-unknown-linux-musl
        include:
        - target: aarch64-apple-darwin
          os: macos-latest
          target_rustflags: ''
        # - target: aarch64-unknown-linux-musl
        #   os: ubuntu-latest
        #   target_rustflags: '--codegen linker=aarch64-linux-gnu-gcc'
        # - target: armv7-unknown-linux-musleabihf
        #   os: ubuntu-latest
        #   target_rustflags: '--codegen linker=arm-linux-gnueabihf-gcc'
        - target: x86_64-apple-darwin
          os: macos-latest
          target_rustflags: ''
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          target_rustflags: ''
        - target: x86_64-unknown-linux-musl
          os: ubuntu-latest
          target_rustflags: ''

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Install Rust Toolchain Components
      uses: actions-rs/toolchain@v1.0.6
      with:
        override: true
        target: ${{ matrix.target }}
        toolchain: stable

    - name: Install AArch64 Toolchain
      if: ${{ matrix.target == 'aarch64-unknown-linux-musl' }}
      run: |
        sudo apt-get update
        sudo apt-get install gcc-aarch64-linux-gnu

    - name: Install ARM7 Toolchain
      if: ${{ matrix.target == 'armv7-unknown-linux-musleabihf' }}
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm*

    - name: Release musd binary
      id: musd
      env:
        TARGET: ${{ matrix.target }}
        REF: ${{ github.ref }}
        OS: ${{ matrix.os }}
        TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
      run: ./bin/release
      shell: bash

    # REF: https://github.com/marketplace/actions/gh-release
    # - name: Publish Archive
    #   uses: softprops/action-gh-release@v0.1.14
    #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
    #   with:
    #     draft: false
    #     files: ${{ steps.musd.outputs.archive }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
